feedname: "base2"
schema_database: "SCHEMA_BASE2_AL00242"
raw_database: "RAW_BASE2_AL00242"
hql: "base2.hql"

# config1 = data_catalog_create_schema_json_config.txt
config1: "True" #When 'true' catalog json will not be created

# config2 = data_catalog_create_ext_entries_config.txt
config2: "True"
entry_group: ""
bucket_name: ""
